# Generated by Django 4.0 on 2023-03-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPIs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSVFile',
            new_name='CSVData',
        ),
    ]
